{% set name = "unitem" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d20d46f1685041659c50498e7abd15a2c80a2a9c57f6a2b2201ecdec57cda1f9

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.21.4
    - svgwrite >=1.4.1
    - maxbin2 >=2.2.7
    - metabat2 >=2.15

test:
  imports:
    - unitem
    - unitem.external
  commands:
    - unitem -h

about:
  home: https://github.com/dparks1134/UniteM
  license: GPL-3
  license_family: GPL
  license_file: LICENSE 
  summary: 'UniteM implementing different ensemble binning strategies for producing a non-redundant set of MAGs.'

extra:
  recipe-maintainers:
    - donovan.parks
